// <auto-generated />
using System;
using KioskZakat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KioskZakat.Migrations
{
    [DbContext(typeof(KioskZakatContext))]
    [Migration("20210427012356_student-database")]
    partial class studentdatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KioskZakat.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("itemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("price")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("KioskZakat.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("couponNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("icNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("itemID")
                        .HasColumnType("int");

                    b.Property<string>("transacTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("validUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("itemID");

                    b.ToTable("Purchase");
                });

            modelBuilder.Entity("KioskZakat.Models.Student", b =>
                {
                    b.Property<string>("noMatric")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("checkout")
                        .HasColumnType("bit");

                    b.Property<string>("kodProgram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("kunci")
                        .HasColumnType("bit");

                    b.Property<string>("nama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noBilik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("semester")
                        .HasColumnType("int");

                    b.Property<byte[]>("time")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("noMatric");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("KioskZakat.Models.Purchase", b =>
                {
                    b.HasOne("KioskZakat.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("itemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
